import axios from 'axios';

const API_URL = 'http://localhost:5000/api/requests';

// Interface for the request data structure
interface RequestData {
  requestId: string;
  createdOn?: string; // Optional because it can be automatically generated by the backend
  location: string;
  service: string;
  status: 'NEW' | 'IN_PROGRESS' | 'ON_HOLD' | 'REJECTED' | 'CANCELLED';
  priority: 'HIGH' | 'MEDIUM' | 'LOW';
  department: string;
  requestedBy: string;
  assignedTo: string;
}

// Function to fetch all requests
export const getRequests = async () => {
  try {
    const response = await axios.get(API_URL);
    return response.data;
  } catch (error) {
    console.error('Error fetching requests:', error);
    throw error;
  }
};

// Function to create a new request
export const createRequest = async (requestData: RequestData) => {
  try {
    const response = await axios.post(API_URL, requestData);
    return response.data;
  } catch (error) {
    console.error('Error creating request:', error);
    throw error;
  }
};

// Function to update an existing request by ID
export const updateRequest = async (id: string, requestData: Partial<RequestData>) => {
  try {
    const response = await axios.patch(`${API_URL}/${id}`, requestData);
    return response.data;
  } catch (error) {
    console.error('Error updating request:', error);
    throw error;
  }
};

// Function to delete a request by ID
export const deleteRequest = async (id: string) => {
  try {
    const response = await axios.delete(`${API_URL}/${id}`);
    return response.data;
  } catch (error) {
    console.error('Error deleting request:', error);
    throw error;
  }
};
